logdir: ./log/
tag: sup_test
model_dir: /storage/model/e2e_asr/uda
model_name: test
load_model_path: /storage/model/e2e_asr/uda/
load_optimizer: True
dataset_root_dir: /storage/feature/wsj/processed/deltatrue
vocab_path: /storage/feature/wsj/processed/deltatrue/vocab_dict.pkl
non_lang_syms_path: /storage/feature/wsj/processed/deltatrue/non_lang_syms.pkl
summary_steps: 50
labeled_set: test_dev93 #train_si84
unlabeled_set: test_dev93 #train_si284
clean_dev_set: test_dev93
noisy_dev_set: test_dev93
test_set: test_eval92
max_feature_length: 2300
min_feature_length: 30
max_text_length: 250
min_text_length: 2
extra_length: 15
max_dec_timesteps: 230
batch_size: 16
shuffle: True
input_dim: 249
enc_hidden_dim: 320
enc_n_layers: 3
subsample: [2, 2, 2]
vgg: False
dropout_rate: 0.3
max_grad_norm: 5
dec_hidden_dim: 320
multi_dec: False
embedding_dim: 128
att_dim: 320
conv_channels: 10
conv_kernel_size: 100
att_odim: 320
heads: 1
init_tf_rate: 1.0
tf_rate_lowerbound: 1.0
tf_decay_epochs: 20
ls_weight: 0.05
weight_decay: 0.000001
gaussian_std: 0.075
add_gaussian: False
gaussian_epoch: 20
learning_rate: 0.0005
lr_gamma: 0.2
epochs: 50
ssl_iterations: 75000
change_learning_rate_epoch: 100
encoder_iterations: 4
unsup_weight: 0.01
sample: False
